# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpagetranslation',
            name='meta_image',
            field=models.ImageField(blank=True, help_text='This allows social media sites to pick a default image.', max_length=100, null=True, verbose_name='example image'),
        ),
    ]
