# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_pages', '0004_add_htmlpage_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlnode',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
