# Generated by Django 3.2.20 on 2023-10-16 12:08

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_pages', '0006_remove_mptt_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlnode_translation',
            name='master',
            field=parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='fluent_pages.urlnode'),
        ),
    ]
